name: "CI / CD"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "deploy react app with vercel"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: "deploy to vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi
          npx vercel --token ${VERCEL_TOKEN} $prodRun
          CI='' npm run build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}